export { Memoic } from './Memoic'
export { query } from './queries'
export { createMemoic } from './createMemoic'
export { apply, seconds } from './utils'
export type { Plugin, Query, Queries } from './types'
